name: Auto Update Pokémon Data

on:
  schedule:
    - cron: '0 2 * * *'  # 每天台灣時間早上10點 (UTC+8)
  workflow_dispatch:     # 手動觸發也可以

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install requests beautifulsoup4 selenium webdriver-manager

    - name: Run updater
      run: python final_pokemon_updater.py

    - name: Commit and push if there are changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add pokemon_data.json images/
        git diff --cached --quiet || git commit -m "🔄 自動更新寶可夢資料"
        git push
